[general]
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 10

#normal = { family = "IosevkaTerm Nerd Font" }
normal = { family = "JetBrainsMono Nerd Font" }

[window]
#dimensions = { columns = 123, lines = 35 }
#
#position = { x = 20 , y = 50 }
#
#opacity = 0.9
#blur = true
#
dynamic_padding = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
