[general]
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font Mono" }

[window]
opacity = 0.8
dynamic_padding = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "block", blinking = "on" }
blink_interval = 1000
blink_timeout = 30

[env]
TERM = "xterm-256color"
