#!/bin/bash

is_in_no_auto_start_bars() {
	no_auto_start_bars=("audio")

	for no_auto_start_bar in ${no_auto_start_bars[@]}; do
		if [[ "$no_auto_start_bar" == "$1" ]]; then
			return 0
		fi
	done

	return 1
}

start_bar() {
	polybar --quiet --reload $1 --config=~/.config/polybar/config/$1-bar.ini &

	PID=$!
	echo $PID > /tmp/$1-bar.pid

	disown
}

kill_bar() {
	polybar-msg -p $(cat /tmp/$1-bar.pid) cmd quit &> /dev/null
}

if [[ $2 == "--kill" ]]; then
	kill_bar $1
elif [[ ! -z $1 ]]; then
	start_bar $1
else
	for bar in $(find ~/.config/polybar/config -name "*-*" -exec basename -s '-bar.ini' "{}" \;); do
		is_in_no_auto_start_bars $bar && continue
		start_bar $bar
	done
fi
